### ISSUE TITLE
Enable http keep-alive

### ISSUE THREAD

**Issue by arontsang** [mholt/acmez#26]
I am currently trying to use caddy with a corporate acme endpoint that is behind an AWS ELB.

Due to the round-robin nature of the ELB, I am unable to do a full http challenge going to the same backend server.

We need either https keep-alive or cookie support to allow caddy to connect to the same server at each stage of the request.

**Comment by mholt** [comment]
Thanks for opening an issue. Caddy is already capable of solving challenges behind a load balancer. This is the acmez repo, was that a mistake? 🤔 just want to make sure I understand what is being asked.

**Comment by arontsang** [comment]
Hi @mholt,
Thanks for your prompt response. I noticed that caddy seems to be using this library for driving the ACME api (not the challenge).

The load balancer is in-front of the ACME endpoint (and not Letsencrypt nor ZeroSSL).

My issue is that caddy is creating a fresh TCP request for each API call (NewNonce, NewAccount etc). The AWS Load Balance is then forwarding the requests to different backend servers (and our vendor seems to not share state between them (or not quickly enough)). The result is that the received nonce is rejected by the NewAccount request by caddy.

**Comment by mholt** [comment]
Thanks; closing this issue, since the feature really has to go downstream.
