### ISSUE TITLE
Enable http cookie jar

### ISSUE THREAD

**Issue by arontsang** [mholt/acmez#27]
I am currently trying to use caddy with a corporate acme endpoint that is behind an AWS ELB.

Due to the round-robin nature of the ELB, I am unable to do a full http challenge going to the same backend server.

I hope we can add a cookie jar to the acme client, so that ELB sticky cookies can route the request back to the same backend server.

**Comment by mholt** [comment]
Do you have an example? I'm not familiar with ELB. If it's as simple as an in memory cookie jar then I don't see why not.

**Comment by arontsang** [comment]
@mholt Yes, an in-memory cookie jar is perfect.

The issue is that I am using a corporate acme endpoint (rather than zerossl/letsencrypt), and that endpoint is behind a round-robin load balancer.

When caddy requests a NewNonce, the request goes to backend A.
When caddy then uses that nonce to call NewAccount, the load balancer forwards the request to backend B (which rejects the nonce).

The cookie is simply for the load balancer to mark a "session" to the same backend A (instead of backend B).

**Comment by mholt** [comment]
As with your other issue #26, you can customize the `http.Client` used (to have a Cookie Jar) here: https://pkg.go.dev/github.com/mholt/acmez/v2@v2.0.0/acme#Client

**Comment by arontsang** [comment]
Thanks I'll see if I can PR caddy

**Comment by mholt** [comment]
Ok -- thanks. I will close this issue then since the feature really has to go downstream.
