### ISSUE TITLE
External Account Binding JWS verification failed

### ISSUE THREAD

**Issue by devhaozi** [mholt/acmez#28]
I tried to use acmez to issue a certificate for [Google Trust Services](https://pki.goog/), but I got the error `External Account Binding JWS verification failed`.

Here is the minimal code that can reproduce the problem.

```go
client := acmez.Client{
	Client: &acme.Client{
		Directory:  "https://dv.acme-v02.api.pki.goog/directory",
		HTTPClient: http.DefaultClient,
	},
}
pk, _ := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
account := acme.Account{
	Contact:              []string{"mailto:test@haozi.net"},
	TermsOfServiceAgreed: true,
	PrivateKey:           pk,
}
account.SetExternalAccountBinding(context.Background(), client.Client, acme.EAB{
	KeyID:  "", // https://cloud.google.com/certificate-manager/docs/public-ca-tutorial
	MACKey: "",
})

account, err := client.NewAccount(context.Background(), account) // HTTP 403 urn:ietf:params:acme:error:unauthorized - External Account Binding JWS verification failed)
```

Is there any step I did wrong?

**Comment by mholt** [comment]
Could you clarify for me, which error are you getting exactly? "JWS verification failed" or "HTTP 400 urn:ietf:params:acme:error:externalAccountRequired" (as in your code comment)? Which line of code gives you which error?

**Comment by devhaozi** [comment]
> ```go
> External Account Binding is required for new accounts
> ```

Strange, the error I encountered before was `External Account Binding JWS verification failed`, but now it has become `External Account Binding is required for new accounts`, the description has been updated.

**Comment by mholt** [comment]
Are you sure the EAB was generated within 7 days? It looks like they're deleted after that if not used to create an account. (Sorry I haven't had a chance to try it yet, as it'd involve me having to set up a Google Cloud account and stuff)

**Comment by devhaozi** [comment]
> Are you sure the EAB was generated within 7 days? It looks like they're deleted after that if not used to create an account. (Sorry I haven't had a chance to try it yet, as it'd involve me having to set up a Google Cloud account and stuff)

Yes, it is newly generated. I can give you one for testing if you need it.

**Comment by devhaozi** [comment]
> > Are you sure the EAB was generated within 7 days? It looks like they're deleted after that if not used to create an account. (Sorry I haven't had a chance to try it yet, as it'd involve me having to set up a Google Cloud account and stuff)
> 
> Yes, it is newly generated. I can give you one for testing if you need it.

`{"key_id":"6367a1ddff9f93b388781702187d9e1e","mac_key":"SHdrdW9NWXZTQkhrbUJtZDVjRDJDUWszY1hoWDF3ZjR1aGM5SFlBOUJCbjdtcUJmNk1LWlR5Ym1RNTY3NnFkSUJRaE9TQW5Hb0JGNlkwbnRodXdHT1E="}`

**Comment by mholt** [comment]
Thanks.

I noticed you're not checking the error returned from `SetExternalAccountBinding()`. I would suggest doing that.

Anyway, I can also see the error now, so thanks for the reproducer.

To be honest, I'm not sure what is wrong. I know our implementation works with pebble (the test ACME server) and also in production, so there might be something funky going on with this ACME provider... have you tried asking Google Cloud support for any more information?

In fact, another popular ACME client has an issue reporting the same error: https://github.com/acmesh-official/acme.sh/issues/4082

I'm beginning to wonder if there's something odd/wrong on Google's end.

**Comment by devhaozi** [comment]
> Thanks.
> 
> I noticed you're not checking the error returned from `SetExternalAccountBinding()`. I would suggest doing that.
> 
> Anyway, I can also see the error now, so thanks for the reproducer.
> 
> To be honest, I'm not sure what is wrong. I know our implementation works with pebble (the test ACME server) and also in production, so there might be something funky going on with this ACME provider... have you tried asking Google Cloud support for any more information?
> 
> In fact, another popular ACME client has an issue reporting the same error: [acmesh-official/acme.sh#4082](https://github.com/acmesh-official/acme.sh/issues/4082)
> 
> I'm beginning to wonder if there's something odd/wrong on Google's end.

I found the reason. Google encoded the `mac_key` returned by the API in base64, so it needs to be decoded first to get the real `mac_key`.

Before:

```
SHdrdW9NWXZTQkhrbUJtZDVjRDJDUWszY1hoWDF3ZjR1aGM5SFlBOUJCbjdtcUJmNk1LWlR5Ym1RNTY3NnFkSUJRaE9TQW5Hb0JGNlkwbnRodXdHT1E=
```

After:
```
HwkuoMYvSBHkmBmd5cD2CQk3cXhX1wf4uhc9HYA9BBn7mqBf6MKZTybmQ5676qdIBQhOSAnGoBF6Y0nthuwGOQ
```

**Comment by mholt** [comment]
Ah, good to know! I wonder why they are base64-encoding the ASCII string. :thinking:
